language: node_js
node_js:
  - "5"
  - "4.1"
  - "4.0"
  - "0.10"
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - npm install
  - npm install -g gulp
script: npm test
notifications:
  email: false
#   slack: mks31:v3TzTDrOf5TAzxkyflH1uzr9
